### ISSUE TITLE
Replace "preset values" with "row labels"

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#34]
Preset values is a weird concept, that would be solved by labeling rows.

**Comment by pax01** [comment]
Hi ajb, great work!

I added a singleMatrix field to formbuilder (works with radios or checkboxes)

{"fields":[{"label":"Matrix","field_type":"singleMatrix","required":true,"field_options":{"rows":[{"label":"first question"},{"label":"second question"}],"cols":[{"label":"good"},{"label":"bad"}],"options":[{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false},{"label":"","checked":false}],"description":"This is a matrix question "},"cid":"c5"}]}

It looks like this:
![singlematrix](https://cloud.githubusercontent.com/assets/1593054/18166252/5ce641ce-704a-11e6-8579-5e11f437d545.png)

Working properly, but now I am migrating to formrenderer-base because it works properly with multi pages... 
Can you please advice on coding the formrender part?

**Comment by ajb** [comment]
Closing in favor of repeating sections.
