### ISSUE TITLE
Multi-page validation behavior

### ISSUE THREAD

**Issue by aviv** [dobtco/formrenderer-base#56]
### Pages with validation errors should *always* have an indication of these errors

Whenever a user leaves a page with validation errors, we should display the circled page number for that page in red. This should persist across refreshes, reloads, and returning to a draft.

### There should be *one* behavior for switching pages

Switching pages with the circled page numbers and switching pages with the bottom status bar buttons should have the same behavior. If we're going to allow users to navigate away from a page that has validation errors, they should be able to do it via either navigation vector.

From chat:

> adam
i think we should change the behavior to only validate when submitting, not paginating
and that fields should also be validated on `blur()`
so that as you're filling out a form, you get instant validation of any mistakes you're making
instead of waiting until you change pages

**Comment by aviv** [comment]
How we do inline validation is distinct from how we display validation errors across multiple pages. What I'm saying is that if there are validation errors on a page, *it should be indicated in the circled page number for that page*.

**Comment by aviv** [comment]
To add in another issue, there should be a way of indicating *where* the validation error has occurred for long forms. The user sees this:

![](http://take.ms/z2rey)

But has to scroll way down to find the actual error:

![](http://take.ms/fFcyT)

**Comment by ajb** [comment]
Lemme work on an "improved validations" branch for formrenderer and show you what I come up with. @jrubenoff, if you have any other "Outcomes" to add to this list, now would be the time!

**Comment by jrubenoff** [comment]
I'm wondering whether we're making a few false assumptions here:

1. Respondents will always fill out the form in a linear fashion
2. Respondents will intuitively understand which button they need to click in order to correct errors

Screendoor forms are often long and cumbersome to the point where I actively want to complete them in a nonlinear fashion. [CFA's](https://screendoor.dobt.co/code-for-america/2015-fellowship-application), for example... I would probably fill out my contact info (Page 1) and portfolio links (Page 4) first, and save the essay questions (Page 3) for last.

If respondents fill out the form in a nonlinear way, we get these bizarre usability issues where you're allowed to go to previous pages to see the errors you've made on them, but can't return to your previous position:

![forms](https://cloud.githubusercontent.com/assets/1328849/6874040/8b45d636-d471-11e4-9df7-02df9fc485be.gif)

Not sure what the best solution is. First thing that comes to mind: Apple abolishes pages in their checkout form in favor of "collapsible sections". It kind of solves the problem but could take up a lot of vertical space.

![screen shot 2015-03-27 at 11 03 18 am](https://cloud.githubusercontent.com/assets/1328849/6874090/fedddde6-d471-11e4-9371-70db1ec8b43a.png)

![screen shot 2015-03-27 at 11 03 13 am](https://cloud.githubusercontent.com/assets/1328849/6874095/027da2e2-d472-11e4-917c-021432dd8150.png)

Let's think of a few more ideas...

**Comment by jrubenoff** [comment]
Also: inline validation on blur would go a long way towards solving this problem, but there's still a problem for required fields that have been left blank, or the last form field on a page.

**Comment by ajb** [comment]
I don't mean to be dismissive, but I think I can solve most of the pressing
issues with a relatively minimal amount of effort, which is why I'm hoping
y'all will be alright with just giving me a week to improve upon what we
have and then present it here.

On Fri, Mar 27, 2015 at 2:16 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Also: inline validation on blur would go a long way towards solving this
> problem, but there's still a problem for required fields that have been
> left blank, or the last form field on a page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87038857>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by aviv** [comment]
Sounds reasonable to me, as it might be easier to have this discussion after the existing behavior has already been improved at least somewhat.

**Comment by ajb** [comment]
Yeah, my main thing here is that we don't need to be visionaries or
re-invent the wheel -- I just should have done a better job following
best-practices when implementing this stuff in the first plcae.

On Fri, Mar 27, 2015 at 2:54 PM, Aviv Nitsan <notifications@github.com>
wrote:

> Sounds reasonable to me, as it might be easier to have this discussion
> after the existing behavior has already been improved at least somewhat.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87053515>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
Can you explain your current thinking, at least?

**Comment by ajb** [comment]
- Run validations (except presence validation) when a field is blurred
- Don't ever validate when switching between pages
- Run all validations when clicking the "Submit" button
- Add a "take me to first error" link to the error_alert

I think this will solve most of the problems described in this thread.

On Fri, Mar 27, 2015 at 3:10 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Can you explain your current thinking, at least?
>
> On Fri, Mar 27, 2015 at 11:56 AM, Adam Becker <notifications@github.com>
> wrote:
>
> > Yeah, my main thing here is that we don't need to be visionaries or
> > re-invent the wheel -- I just should have done a better job following
> > best-practices when implementing this stuff in the first plcae.
> >
> > On Fri, Mar 27, 2015 at 2:54 PM, Aviv Nitsan <notifications@github.com>
> > wrote:
> >
> > > Sounds reasonable to me, as it might be easier to have this discussion
> > > after the existing behavior has already been improved at least
> somewhat.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87053515
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Adam Becker
> > (951) 9-BECKER
> > @AdamJacobBecker
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87054379
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-87061071>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by jrubenoff** [comment]
Ping... what's the progress on this? It would be great to get this out alongside respondent view.

**Comment by ajb** [comment]
Haven't had time. Still on my list.

On Fri, Apr 3, 2015 at 8:59 PM, Josh Rubenoff <notifications@github.com>
wrote:

> Ping... what's the progress on this? It would be great to get this out
> alongside respondent view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dobtco/formrenderer-base/issues/56#issuecomment-89476036>
> .
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker
