### ISSUE TITLE
Improved character count

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#59]
![img](http://take.ms/3wy03)

**Comment by jrubenoff** [comment]
Here's my [respondent view changes](https://github.com/dobtco/screendoor-v2/pull/1526/files#diff-9e8adf4bbfe33666e7affd929a9dac2dR175). Screenshotted:

![screen shot 2015-04-07 at 10 44 21 am](https://cloud.githubusercontent.com/assets/1328849/7029519/13522166-dd13-11e4-9ce3-6fbd3a3fd043.png)

- Add a wrapper `div` to the `textarea`
- Remove the units from the character counter (we already have "less than 300 characters / words" in the helper text)
- Place the character counter within it, position absolutely
- Add CSS classes to the wrapper when the count is too low / high

One problem: the counter may overlap the content of the `textarea`. This isn't an issue in respondent view because there's a healthy amount of padding on form elements.
