### ISSUE TITLE
Better handling of prefixes

### ISSUE THREAD

**Issue by ajb** [dobtco/formrenderer-base#62]
![img](http://dobt-captured.s3.amazonaws.com/ajb/Write_response_-_Screendoor_2015-04-23_08-51-20.png)

![img](http://dobt-captured.s3.amazonaws.com/ajb/Write_response_-_Screendoor_2015-04-23_08-51-16.png)

@jrubenoff is there anything we can do to prevent users from hitting these errors? We could strip out any non-digits when the field is blurred... but that seems potentially jarring.

**Comment by jrubenoff** [comment]
Ideally, just keep 'em in, but strip them out on the preview page.

Also, instead of "stripping out any non-digits", let's make sure the prefix matches the one outside the input field. I can imagine someone typing `400 AUD` or `£50` into a price field... don't want to accidentally perform a false currency conversion.

**Comment by ajb** [comment]
Ok, so we can ignore duplicate prefixes/suffixes when validating, and strip them out in `normalize_responses` (the same place where we normalize URLs to include `http://`, for example.)
